In [ ]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv("/content/credit_card_approval_dataset.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Candidate Name  1000 non-null   object
 1   Age             1000 non-null   int64
 2   Gender          1000 non-null   object
 3   Salary          1000 non-null   int64
 4   Income          1000 non-null   int64
 5   Job Details     1000 non-null   object
 6   Credit History  1000 non-null   object
 7   Credit Score    1000 non-null   int64
 8   Existing Loans  1000 non-null   int64
 9   Credit Status   1000 non-null   object
dtypes: int64(5), object(5)
memory usage: 78.3+ KB

In [10]:
df.isnull().sum()

Candidate Name    0
Age               0
Gender            0
Salary            0
Income            0
Job Details       0
Credit History    0
Credit Score      0
Existing Loans    0
Credit Status     0
dtype: int64

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.fillna("Unknown",inplace=True)

In [15]:
df.columns=df.columns.str.strip()

In [14]:
df.to_csv("cleaned_dataset.csv",index=False)

In [13]:
salary = np.array(df["Salary"])
credit_score = np.array(df["Credit Score"])
salary

array([72978, 85895, 58514, 94444, 20894, 24904, 78786, 91788, 39546,
       39419, 54563, 50459, 76147, 54088, 49181, 63188, 90542, 28577,
       50087, 66546, 71481, 46099, 58931, 65605, 42441, 49762, 84845,
       81089, 66136, 78006, 88298, 63738, 65005, 62771, 69946, 89042,
       35482, 41547, 29405, 31188, 75164, 50165, 34000, 75000, 69609,
       98577, 53506, 95886, 50211, 66896, 48877, 39617, 40791, 72688,
       37850, 59785, 37035, 66605, 43086, 77081, 52342, 53988, 25564,
       35285, 25973, 59613, 92653, 30910, 37058, 47304, 68057, 96063,
       68752, 49457, 57603, 41562, 54042, 73328, 51040, 51497, 31396,
       27502, 80766, 29976, 21689, 48695, 91347, 98711, 56459, 46969,
       47609, 68047, 54899, 34589, 80544, 47668, 31533, 93966, 83341,
       89504, 76498, 59526, 47886, 54716, 40146, 53997, 66627, 74867,
       65542, 59117, 51207, 38307, 32054, 24824, 72114, 60228, 82781,
       78238, 36758, 22192, 88057, 61547, 50229, 81254, 42007, 95182,
       78538, 23576, 51085, 45829, 97613, 65967, 62559, 91723, 50927,
       80442, 90948, 72423, 92408, 62045, 80794, 81832, 44203, 37885,
       68917, 77677, 77592, 49773, 77527, 68340, 75287, 84062, 34790,
       26820, 90805, 75537, 44505, 79771, 96231, 46449, 58792, 82876,
       42751, 45466, 96291, 41556, 21652, 47107, 56591, 99211, 32336,
       81608, 69184, 92559, 68205, 67927, 70194, 66098, 87566, 31116,
       94731, 65168, 81219, 92150, 94877, 56773, 71288, 97297, 43735,
       29125, 97805, 29052, 75641, 93753, 85775, 98255, 57748, 38999,
       77552, 55076, 91040, 99132, 27058, 76034, 91471, 22561, 73280,
       75152, 90096, 45883, 42267, 61841, 56901, 70112, 85529, 82050,
       33307, 35615, 86717, 52921, 55901, 55675, 65974, 60746, 85799,
       61005, 78684, 59267, 55656, 76220, 44850, 60579, 53662, 47341,
       83952, 80935, 23927, 90635, 47377, 84445, 93098, 53967, 96260,
       55708, 83033, 48431, 37370, 76849, 84743, 22904, 22891, 36576,
       54491, 53980, 98496, 59791, 68212, 73942, 55759, 79782, 82823,
       83960, 45322, 24054, 94378, 39535, 83000, 68048, 67388, 75106,
       78757, 86322, 39700, 32638, 66085, 54047, 46720, 76553, 86374,
       89046, 42430, 81981, 77680, 91154, 86341, 77535, 85854, 32867,
       57724, 72148, 59044, 92500, 23564, 67599, 72508, 99958, 42719,
       58520, 34426, 57287, 92960, 57228, 88005, 70086, 84585, 34093,
       78784, 27712, 88418, 32161, 37207, 57507, 47621, 84192, 69885,
       97386, 96641, 31200, 58876, 54654, 53067, 88293, 24075, 32167,
       72738, 32031, 51545, 47219, 38094, 33271, 91057, 74624, 99906,
       52098, 61281, 61054, 62803, 49230, 60119, 67631, 89659, 82338,
       94399, 62183, 74310, 93109, 31011, 56847, 93409, 96215, 88332,
       94962, 99150, 26315, 36266, 22538, 60870, 56318, 71172, 55257,
       56459, 94445, 41291, 66011, 73958, 53607, 98965, 50888, 26075,
       27656, 73167, 84047, 93974, 54105, 98506, 92509, 21805, 35401,
       86576, 40562, 52990, 28943, 49672, 84060, 76860, 70523, 20776,
       62740, 30031, 92626, 69296, 26447, 43477, 42328, 53041, 75457,
       26162, 60907, 25108, 44882, 22207, 57070, 63367, 91467, 88212,
       42884, 95309, 77278, 27776, 47435, 68403, 54398, 37876, 33819,
       70678, 65159, 83600, 95205, 53600, 21852, 98728, 30067, 45784,
       67941, 45986, 29323, 35051, 48946, 65392, 38099, 24453, 56253,
       53016, 48976, 47655, 81827, 83288, 23696, 54076, 86575, 70444,
       36631, 94801, 31383, 29463, 92014, 60253, 55013, 94345, 39135,
       79151, 55033, 29542, 59693, 72297, 26870, 59536, 81905, 84920,
       73602, 63840, 74256, 95990, 58355, 74447, 37684, 69563, 36387,
       25008, 76510, 96701, 71529, 22931, 80503, 67423, 91105, 57394,
       22683, 76031, 31163, 22815, 92515, 59874, 58341, 75302, 33409,
       21867, 38336, 54080, 77313, 53361, 89004, 27721, 66616, 78759,
       52123, 49753, 50424, 83518, 48915, 92655, 53297, 31649, 37771,
       73874, 23209, 32328, 47787, 43297, 57396, 81164, 69446, 28603,
       23963, 75598, 86167, 59401, 34740, 29048, 82734, 75032, 35683,
       37289, 20848, 38117, 47604, 92829, 44715, 88361, 62573, 38222,
       70095, 83230, 66824, 68011, 95575, 60628, 43497, 25727, 57291,
       67572, 61907, 41522, 75077, 57754, 83176, 49107, 60516, 54999,
       48566, 95255, 96353, 81576, 93621, 95662, 61963, 35249, 36118,
       39689, 73872, 52449, 43027, 93699, 88868, 79954, 28446, 50816,
       76914, 46208, 70350, 75726, 54690, 82468, 89363, 38186, 62655,
       81317, 53996, 79046, 93796, 81755, 27997, 24260, 89762, 37333,
       43771, 65189, 75810, 49330, 66844, 88715, 98928, 91034, 61580,
       69469, 39391, 98739, 39144, 60150, 52893, 71711, 97362, 92427,
       27917, 56762, 73138, 79401, 51430, 70554, 86485, 63960, 70271,
       76659, 99853, 81077, 99505, 28590, 23147, 68795, 81452, 28749,
       52690, 56238, 29862, 46698, 42329, 70189, 45287, 70404, 29215,
       61745, 58683, 22983, 76891, 62132, 94579, 39507, 35197, 43362,
       37014, 96506, 38396, 21866, 89165, 89966, 58717, 98342, 48057,
       54806, 40470, 79671, 66274, 45127, 41255, 97548, 72957, 90969,
       30470, 81627, 59634, 78680, 57251, 68615, 44288, 40324, 80162,
       96987, 92255, 58949, 43599, 41060, 28651, 21441, 77330, 75626,
       51268, 87343, 36664, 47067, 95030, 65849, 40856, 23560, 88156,
       28773, 38879, 45972, 25899, 48490, 51999, 35023, 76394, 21778,
       78951, 86804, 74582, 73245, 31861, 57988, 30505, 49624, 69543,
       29813, 90266, 85019, 96856, 78319, 40415, 71507, 40077, 31750,
       32292, 27553, 26773, 54988, 79075, 71359, 49720, 85006, 47934,
       68329, 67922, 30079, 65619, 85399, 97215, 28942, 35941, 63127,
       81720, 20550, 55871, 43972, 30274, 20750, 21125, 56730, 34397,
       33657, 24251, 70854, 90836, 53688, 34857, 62231, 66648, 46793,
       55621, 90085, 78140, 79955, 55868, 55791, 65354, 53081, 79122,
       71458, 99946, 76749, 83352, 88713, 66483, 31672, 36448, 44491,
       62436, 59976, 45844, 82371, 77923, 34881, 26894, 58764, 69987,
       46637, 38055, 79355, 39630, 83878, 29344, 53213, 54030, 85571,
       93284, 89958, 91038, 43310, 74164, 74357, 39169, 29953, 90419,
       74571, 42800, 42773, 58704, 76606, 87522, 26771, 79574, 30280,
       49045, 63555, 74739, 73100, 79995, 35082, 80228, 34589, 36268,
       23855, 83483, 84156, 98112, 24205, 44894, 96170, 84384, 94542,
       51188, 33424, 70153, 27675, 67801, 77211, 59633, 71848, 98764,
       49301, 76973, 85012, 39690, 56236, 92696, 59632, 55300, 33375,
       68727, 75793, 40254, 97953, 66118, 53482, 24296, 75668, 41228,
       86881, 43092, 39657, 32649, 49093, 75449, 92518, 39795, 68478,
       20432, 35372, 58921, 95070, 84848, 64013, 39654, 49937, 57918,
       86880, 37604, 66453, 61287, 70002, 94642, 51031, 22174, 37152,
       87872, 59421, 95665, 65249, 84950, 77013, 25309, 69764, 78417,
       31172, 34083, 78578, 68549, 58335, 63352, 82802, 62564, 52023,
       31912, 45749, 35034, 37953, 68696, 59455, 64771, 76526, 76735,
       53583, 68553, 66875, 23331, 70565, 99281, 84047, 36357, 29056,
       79538, 88403, 37924, 70757, 56904, 31263, 58362, 36137, 57011,
       64797, 20029, 23625, 74547, 51012, 74265, 65207, 22131, 21916,
       90118, 46774, 22354, 45843, 23744, 55744, 56780, 66939, 89534,
       45927, 33531, 67379, 75907, 78563, 78251, 74034, 70152, 50003,
       60832, 39004, 59664, 20175, 69098, 53408, 68654, 84817, 68846,
       39263, 26069, 46248, 84210, 92230, 99869, 31313, 55852, 58716,
       38930, 84183, 83650, 37672, 20474, 88053, 38070, 69415, 22231,
       98889, 48435, 22112, 97253, 89642, 59576, 99286, 24601, 31545,
       29687, 32187, 64875, 94818, 35427, 33852, 80536, 51414, 51143,
       54264, 34293, 77992, 46504, 21511, 57868, 90289, 90509, 57329,
       66736])

In [16]:
np.mean(df['Salary'])

np.float64(60566.878)

In [17]:
np.median(df['Salary'])

np.float64(59832.5)

In [18]:
np.std(df['Salary'])

22354.38398039892

In [20]:
np.var(df['Credit Score'])

29299.38543600003

In [19]:
m=np.min(salary)
n=np.max(salary)
m,n

(np.int64(20029), np.int64(99958))

In [21]:
np.sum(salary)

np.int64(60566878)

In [22]:
high_salary = salary[salary > 50000]
high_salary

array([72978, 85895, 58514, 94444, 78786, 91788, 54563, 50459, 76147,
       54088, 63188, 90542, 50087, 66546, 71481, 58931, 65605, 84845,
       81089, 66136, 78006, 88298, 63738, 65005, 62771, 69946, 89042,
       75164, 50165, 75000, 69609, 98577, 53506, 95886, 50211, 66896,
       72688, 59785, 66605, 77081, 52342, 53988, 59613, 92653, 68057,
       96063, 68752, 57603, 54042, 73328, 51040, 51497, 80766, 91347,
       98711, 56459, 68047, 54899, 80544, 93966, 83341, 89504, 76498,
       59526, 54716, 53997, 66627, 74867, 65542, 59117, 51207, 72114,
       60228, 82781, 78238, 88057, 61547, 50229, 81254, 95182, 78538,
       51085, 97613, 65967, 62559, 91723, 50927, 80442, 90948, 72423,
       92408, 62045, 80794, 81832, 68917, 77677, 77592, 77527, 68340,
       75287, 84062, 90805, 75537, 79771, 96231, 58792, 82876, 96291,
       56591, 99211, 81608, 69184, 92559, 68205, 67927, 70194, 66098,
       87566, 94731, 65168, 81219, 92150, 94877, 56773, 71288, 97297,
       97805, 75641, 93753, 85775, 98255, 57748, 77552, 55076, 91040,
       99132, 76034, 91471, 73280, 75152, 90096, 61841, 56901, 70112,
       85529, 82050, 86717, 52921, 55901, 55675, 65974, 60746, 85799,
       61005, 78684, 59267, 55656, 76220, 60579, 53662, 83952, 80935,
       90635, 84445, 93098, 53967, 96260, 55708, 83033, 76849, 84743,
       54491, 53980, 98496, 59791, 68212, 73942, 55759, 79782, 82823,
       83960, 94378, 83000, 68048, 67388, 75106, 78757, 86322, 66085,
       54047, 76553, 86374, 89046, 81981, 77680, 91154, 86341, 77535,
       85854, 57724, 72148, 59044, 92500, 67599, 72508, 99958, 58520,
       57287, 92960, 57228, 88005, 70086, 84585, 78784, 88418, 57507,
       84192, 69885, 97386, 96641, 58876, 54654, 53067, 88293, 72738,
       51545, 91057, 74624, 99906, 52098, 61281, 61054, 62803, 60119,
       67631, 89659, 82338, 94399, 62183, 74310, 93109, 56847, 93409,
       96215, 88332, 94962, 99150, 60870, 56318, 71172, 55257, 56459,
       94445, 66011, 73958, 53607, 98965, 50888, 73167, 84047, 93974,
       54105, 98506, 92509, 86576, 52990, 84060, 76860, 70523, 62740,
       92626, 69296, 53041, 75457, 60907, 57070, 63367, 91467, 88212,
       95309, 77278, 68403, 54398, 70678, 65159, 83600, 95205, 53600,
       98728, 67941, 65392, 56253, 53016, 81827, 83288, 54076, 86575,
       70444, 94801, 92014, 60253, 55013, 94345, 79151, 55033, 59693,
       72297, 59536, 81905, 84920, 73602, 63840, 74256, 95990, 58355,
       74447, 69563, 76510, 96701, 71529, 80503, 67423, 91105, 57394,
       76031, 92515, 59874, 58341, 75302, 54080, 77313, 53361, 89004,
       66616, 78759, 52123, 50424, 83518, 92655, 53297, 73874, 57396,
       81164, 69446, 75598, 86167, 59401, 82734, 75032, 92829, 88361,
       62573, 70095, 83230, 66824, 68011, 95575, 60628, 57291, 67572,
       61907, 75077, 57754, 83176, 60516, 54999, 95255, 96353, 81576,
       93621, 95662, 61963, 73872, 52449, 93699, 88868, 79954, 50816,
       76914, 70350, 75726, 54690, 82468, 89363, 62655, 81317, 53996,
       79046, 93796, 81755, 89762, 65189, 75810, 66844, 88715, 98928,
       91034, 61580, 69469, 98739, 60150, 52893, 71711, 97362, 92427,
       56762, 73138, 79401, 51430, 70554, 86485, 63960, 70271, 76659,
       99853, 81077, 99505, 68795, 81452, 52690, 56238, 70189, 70404,
       61745, 58683, 76891, 62132, 94579, 96506, 89165, 89966, 58717,
       98342, 54806, 79671, 66274, 97548, 72957, 90969, 81627, 59634,
       78680, 57251, 68615, 80162, 96987, 92255, 58949, 77330, 75626,
       51268, 87343, 95030, 65849, 88156, 51999, 76394, 78951, 86804,
       74582, 73245, 57988, 69543, 90266, 85019, 96856, 78319, 71507,
       54988, 79075, 71359, 85006, 68329, 67922, 65619, 85399, 97215,
       63127, 81720, 55871, 56730, 70854, 90836, 53688, 62231, 66648,
       55621, 90085, 78140, 79955, 55868, 55791, 65354, 53081, 79122,
       71458, 99946, 76749, 83352, 88713, 66483, 62436, 59976, 82371,
       77923, 58764, 69987, 79355, 83878, 53213, 54030, 85571, 93284,
       89958, 91038, 74164, 74357, 90419, 74571, 58704, 76606, 87522,
       79574, 63555, 74739, 73100, 79995, 80228, 83483, 84156, 98112,
       96170, 84384, 94542, 51188, 70153, 67801, 77211, 59633, 71848,
       98764, 76973, 85012, 56236, 92696, 59632, 55300, 68727, 75793,
       97953, 66118, 53482, 75668, 86881, 75449, 92518, 68478, 58921,
       95070, 84848, 64013, 57918, 86880, 66453, 61287, 70002, 94642,
       51031, 87872, 59421, 95665, 65249, 84950, 77013, 69764, 78417,
       78578, 68549, 58335, 63352, 82802, 62564, 52023, 68696, 59455,
       64771, 76526, 76735, 53583, 68553, 66875, 70565, 99281, 84047,
       79538, 88403, 70757, 56904, 58362, 57011, 64797, 74547, 51012,
       74265, 65207, 90118, 55744, 56780, 66939, 89534, 67379, 75907,
       78563, 78251, 74034, 70152, 50003, 60832, 59664, 69098, 53408,
       68654, 84817, 68846, 84210, 92230, 99869, 55852, 58716, 84183,
       83650, 88053, 69415, 98889, 97253, 89642, 59576, 99286, 64875,
       94818, 80536, 51414, 51143, 54264, 77992, 57868, 90289, 90509,
       57329, 66736])

In [23]:
df.groupby("Credit Status")["Salary"].mean()

Credit Status
Approved    69977.958333
Rejected    59567.471239
Name: Salary, dtype: float64

In [24]:
df["Credit Status"].value_counts()

Credit Status
Rejected    904
Approved     96
Name: count, dtype: int64

In [25]:
np.mean(df['Credit Status'] == 'Approved')

np.float64(0.096)